# 闲鱼API接口配置
API_ENDPOINTS:
  # 登录状态检查接口
  login_check: https://passport.goofish.com/newlogin/hasLogin.do
  # 消息头部信息接口
  message_headinfo: https://h5api.m.goofish.com/h5/mtop.idle.trade.pc.message.headinfo/1.0/
  # Token获取接口
  token: https://h5api.m.goofish.com/h5/mtop.taobao.idlemessage.pc.login.token/1.0/

# 应用配置
APP_CONFIG:
  api_version: '1.0'  # API版本
  app_key: 444e9908a51d1cb236a27862abc769c9  # 应用密钥
  app_version: '1.0'  # 应用版本
  platform: web  # 平台类型

# 自动回复配置
AUTO_REPLY:
  api:
    enabled: false  # 是否启用API自动回复
    timeout: 10     # API请求超时时间（秒）
    url: http://localhost:8080/xianyu/reply  # 自动回复API地址
  default_message: 亲爱的"{send_user_name}" 老板你好！所有宝贝都可以拍，秒发货的哈~不满意的话可以直接申请退款哈~  # 默认回复消息
  enabled: true  # 是否启用自动回复
  max_retry: 3  # 最大重试次数
  retry_interval: 5  # 重试间隔（秒）

# Cookie配置
COOKIES:
  last_update_time: '2025-07-05 14:26:16'  # Cookie最后更新时间
  value:  cookie2=1d147f51654dbcf815c6544cf3fc2eab; t=f55fc9831d8f86a1186a72feb76c51d1; _tb_token_=7db3e7be3e10f; _samesite_flag_=true; cna=SaTvIJNxlikCAXBg53pJzWKh; xlly_s=1; sgcookie=E100aICKt6azL7cRAo%2BYZB%2FopqJgbw6s3F%2FTjwyblX6xfiCHyhcPtSaZ976%2FON2FCIn4rClnrwjiBny%2BgZXJsp%2B2YKqU6wYsBXwi%2FTQpRj7aWIs%3D; tracknick=%E6%AD%A4%E6%83%85%E9%9D%9E%E5%8F%AF%E5%BE%85; csg=239c31c4; unb=1634476153; isg=BE5OFJznqtHiwx71HksNreOrnyIQzxLJ25_dBXiXg9EM2-814Ft12MHYFge3cQrh; mtop_partitioned_detect=1; _m_h5_tk=2a5cfa62119219481c69b403f87c9160_1751704821228; _m_h5_tk_enc=5b54ebf988b7f4a22cece6b0d82e14a5; x5sec=7b22733b32223a2235373761623862653133626437633666222c22617365727665723b33223a22307c434b61536f384d47454c2f68715a4d43476777784e6a4d304e4463324d54557a4f7a457739716e4a69774d3d227d; tfstk=gMQZ7ksRaEXCwpv9jwTqLXK9qfY9WEy7nZ9XisfD1dvGlCYViO9Bfnb65toVCsBXmRL1u9JhIcvG1K6Vip5u6dZYXtSFCTYff1N9nKXfeGtDlRIUg9XR1n_VMqRcitF9h5EC61Lvo8w50z1O6Cf5CVNSSvVDgIogOh4mUGVpo8w7PDGHXRTchtsLeJ5HpIRmSEXDKevpMVYDInDnxQvHoExDsB0HGIGijKx0T6vpiEvcnhVexpdms2-e4yRkjSeVtsariDKXE1vEo4cJ_hX0yp0mowRNbLfitq0c8C-N-nDoHALcj16eVGyr7ECG2tdlIA2wTN5PugX3RV8Vtgb2-w2nOdjRTZ81SSaM-NWNSHWmg-RdVQ52VMNm4psc9w-F7uGv9N1cW3TuyAvfA_72gZeY8T5GQgxlSASyexd35yQAbxmDjBdeFWPEmvLY2KgZvynxDHXXTLNO6mnvj8AeFWPEDmKtTBJ761C.. #登录闲鱼网页版，填你的Cookie

# 默认请求头配置
DEFAULT_HEADERS:
  accept: application/json
  accept-language: zh-CN,zh;q=0.9
  cache-control: no-cache
  origin: https://www.goofish.com
  pragma: no-cache
  priority: u=1, i
  referer: https://www.goofish.com/
  sec-ch-ua: '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"'
  sec-ch-ua-mobile: ?0
  sec-ch-ua-platform: '"Windows"'
  sec-fetch-dest: empty
  sec-fetch-mode: cors
  sec-fetch-site: same-site
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

# WebSocket心跳配置
HEARTBEAT_INTERVAL: 15  # 心跳间隔（秒）
HEARTBEAT_TIMEOUT: 5   # 心跳超时时间（秒）

# 日志配置
LOG_CONFIG:
  compression: zip  # 日志压缩格式
  format: '<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'  # 日志格式
  level: INFO  # 日志级别
  retention: 7 days  # 日志保留时间
  rotation: 1 day  # 日志轮转周期

# 人工接管模式配置
MANUAL_MODE:
  timeout: 3600  # 人工接管超时时间（秒）
  toggle_keywords:  # 触发人工接管的关键词
  - 。

# 消息过期时间（毫秒）
MESSAGE_EXPIRE_TIME: 300000

# Token刷新配置
TOKEN_REFRESH_INTERVAL: 3600  # Token刷新间隔（秒）
TOKEN_RETRY_INTERVAL: 300     # Token重试间隔（秒）

# WebSocket请求头配置
WEBSOCKET_HEADERS:
  Accept-Encoding: gzip, deflate, br, zstd
  Accept-Language: zh-CN,zh;q=0.9
  Cache-Control: no-cache
  Connection: Upgrade
  Host: wss-goofish.dingtalk.com
  Origin: https://www.goofish.com
  Pragma: no-cache
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

# WebSocket连接地址
WEBSOCKET_URL: wss://wss-goofish.dingtalk.com/
